---
title: "Read and Wrangle NOW data"
author: "Carlos Calderon"
date: "2025-03-20"
output: html_document
---

First, you have to download the fossil occurrences directly from the NOW site.

The directory where the NOW raw data was saved:

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
# knitr::opts_knit$set(root.dir = "C:/Users/carlo/OneDrive/Desktop/Post_doc_SP/workshop_Tiago")  # Adjust path

#knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

```{r, eval = FALSE}
dir_path <- here::here("raw_files")
```

List all files in the directory and find the file that contains "now" or "NOW"


```{r, eval = FALSE}
 
files <- list.files(dir_path, full.names = TRUE)

target_file <- files[grepl("now", files, ignore.case = TRUE)]
```

Check if a file was found

```{r, eval = FALSE}

if (length(target_file) == 0) {
  stop("No file containing 'now' or 'NOW' found in the directory.")
} else if (length(target_file) > 1) {
  stop("Multiple files match. Please specify further.")
}
```

Read the NOW file and data wrangling

```{r, eval = FALSE}
df <- read.delim(target_file,
                 header = FALSE, sep = "\t", na.strings = c("\\N", "-"),
                 row.names = NULL) 

colnames(df) <- df[1,]

df <- df[-1,]
```


Create a directory where to save the NOW output

```{r, eval = FALSE}
dir <- "NOW_output"
if (!dir.exists(dir)) {
  dir.create(dir)
}
```

Naming the NOW file and saving it as csv format

```{r, eval = FALSE}
output_file <- paste0(dir, "/now_cleaned.csv")

write.csv(df, file = output_file)
```

