---
title: "Tarefas"
author: "Thaís Gomes Piazza Faria"
format: html
---

## Harmonization functions and guide

-   [ ] Checagem da coluna de autores
-   [ ] Explicação da função harmonize_exact_match
-   [ ] Checar o que acontece caso a pessoa chegue com uma lista de nomes repetidos
-   [ ] Permitir que outras colunas (tipo pbdb_internal_synonym) seja preservada no resultado dos matchings, e consertar lá na parte de passo específico
-   [x] Criar funções para lidar com subgêneros
-   [x] Reescrever a última parte para usar as funções de subgênero
-   [ ] Explicação das funções de subgênero
-   [x] Oferecer as opções de deletar objetos que não vão mais ser usados em cada parte do script
-   [ ] Oferecer uma função de checagem de sinônimos numa sinonímia atribuídos a mais de um nome aceito (caso de pbdb_taxon_name == "Canis variabilis")
-   [x] Transformar o trecho de passar pra sinonímia os aceitos em uma função, e adicionar um distinct() no final
    -   [ ] Escrever instruções direitinho
    -   [ ] Colocar umas checagens de argumentos
-   [ ] Arrumar os nomes das variáveis na parte específica
-   [ ] Adicionar a coluna do nome aceito na sinonímia do lado do sinônimo

## pbdb_taxa_species-names

-   [ ] transformar em .qmd comentado pro site
-   [ ] passar as funções de apoio pra um source
-   [ ] Adicionar as partes que Lucas e Carlos colocam nos scripts deles
-   [ ] expandir pra outros ranks taxonômicos que não espécie
-   [ ] transformar a parte de filtragem em uma função
